#!/usr/bin/env python3
"""
hands/scripts/history_insights.py
Safely analyzes ~/.zsh_history for repeated commands and command chains, then
suggests shell aliases or workspace automations. Read-only on history; writes
a report to spine/audit/shell_insights.md.

Usage: history-insights [--top N]
Privacy: lines containing likely secrets are skipped entirely; the report
stores command patterns only, never full argument values for skipped lines.
"""

import os
import re
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

WORKSPACE = Path(os.path.expanduser("~/SuneelWorkSpace"))
HISTORY = Path.home() / ".zsh_history"
REPORT = WORKSPACE / "spine/audit/shell_insights.md"

SECRET_RE = re.compile(
    r"password|passwd|token|secret|api[_-]?key|authorization|bearer|BEGIN [A-Z]+ PRIVATE KEY",
    re.I)
# zsh extended history: ': 1719800000:0;actual command'
EXT_RE = re.compile(r"^: \d+:\d+;")


def load_commands() -> list[str]:
    if not HISTORY.exists():
        return []
    cmds: list[str] = []
    for raw in HISTORY.read_text(errors="ignore").splitlines():
        line = EXT_RE.sub("", raw).strip()
        if not line or SECRET_RE.search(line):
            continue
        cmds.append(line)
    return cmds


def alias_suggestions(counts: Counter, chain_counts: Counter, top: int) -> list[str]:
    suggestions: list[str] = []
    for cmd, n in counts.most_common(50):
        if n < 5 or len(cmd) < 15:
            continue  # only long, genuinely repeated commands earn an alias
        slug = re.sub(r"[^a-z0-9]+", "-", cmd.split()[0].lower()).strip("-")[:12]
        suggestions.append(
            f"`{cmd[:70]}` ran {n}× → consider: `alias {slug}{n % 10}='{cmd[:70]}'`")
        if len(suggestions) >= top:
            break
    for chain, n in chain_counts.most_common(20):
        if n < 3:
            continue
        suggestions.append(
            f"chain `{chain[:80]}` ran {n}× in sequence → candidate for a hands/bin script")
        if len(suggestions) >= top * 2:
            break
    return suggestions


def main() -> int:
    top = 10
    if "--top" in sys.argv:
        try:
            top = int(sys.argv[sys.argv.index("--top") + 1])
        except (IndexError, ValueError):
            pass

    cmds = load_commands()
    if not cmds:
        print(f"history-insights: no readable history at {HISTORY}")
        return 1

    counts = Counter(cmds)
    first_words = Counter(c.split()[0] for c in cmds if c.split())
    chains = Counter(f"{a}  →  {b}" for a, b in zip(cmds, cmds[1:]) if a != b)
    suggestions = alias_suggestions(counts, chains, top)

    ts = datetime.now(timezone.utc).isoformat()
    suggestion_lines = [f"- {s}" for s in suggestions] or \
        ["- nothing repeated enough to automate yet"]
    lines = [
        f"\n## {ts} — shell insights",
        f"\n- Commands analyzed: {len(cmds)} ({len(counts)} unique)",
        "\n### Top tools\n",
        *[f"- `{w}`: {n}×" for w, n in first_words.most_common(top)],
        "\n### Repeated commands (top)\n",
        *[f"- {n}× `{c[:90]}`" for c, n in counts.most_common(top)],
        "\n### Suggestions\n",
        *suggestion_lines,
    ]
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    header = "" if REPORT.exists() else "# Shell Insights\n\nGenerated by `history-insights`.\n"
    with open(REPORT, "a") as f:
        f.write(header + "\n".join(lines) + "\n")

    print(f"[history-insights] {len(cmds)} commands analyzed → {REPORT}")
    for s in suggestions[:top]:
        print(f"  • {s}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
